server {
    listen 80;
    listen [::]:80;
    server_name maxi.kirtarget.ru;

    location = /healthz {
        proxy_pass http://127.0.0.1:18082/healthz;
        proxy_http_version 1.1;
        include proxy_params;
    }

    location ^~ /api/ {
        proxy_pass http://127.0.0.1:18082;
        proxy_http_version 1.1;
        include proxy_params;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location ^~ /admin/ {
        proxy_pass http://127.0.0.1:18082;
        proxy_http_version 1.1;
        include proxy_params;
    }

    location / {
        proxy_pass http://127.0.0.1:13002;
        proxy_http_version 1.1;
        include proxy_params;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
